<?php

$GLOBALS["catalogue_a"] =  array(
    array("nom" => "Poele Beaulieu" , "description" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis est diam. Integer mauris sapien, tempor vel scelerisque vel, vulputate nec nisl. Vivamus euismod elementum pulvinar. Sed accumsan semper fermentum.", "catégorie" => "Gravier", "prix" => 51.10, "image" => "./media/casserole1.webp"),
    array("nom" => "Casserolle X " , "description" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis est diam. Integer mauris sapien, tempor vel scelerisque vel, vulputate nec nisl. Vivamus euismod elementum pulvinar. Sed accumsan semper fermentum.", "catégorie" => "Gravier", "prix" => 24.13, "image" => "./media/casserole2.png"),
    array("nom" => "Poele Richmond" , "description" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis est diam. Integer mauris sapien, tempor vel scelerisque vel, vulputate nec nisl. Vivamus euismod elementum pulvinar. Sed accumsan semper fermentum.", "catégorie" => "Gravier", "prix" => 61.99, "image" => "./media/casserole3.jpg"),
    array("nom" => "Poele Parisienne" , "description" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis est diam. Integer mauris sapien, tempor vel scelerisque vel, vulputate nec nisl. Vivamus euismod elementum pulvinar. Sed accumsan semper fermentum.", "catégorie" => "Gravier", "prix" => 81.60, "image" => "./media/casserole4.png"),
    array("nom" => "Poelle jumelle" , "description" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis est diam. Integer mauris sapien, tempor vel scelerisque vel, vulputate nec nisl. Vivamus euismod elementum pulvinar. Sed accumsan semper fermentum.", "catégorie" => "Gravier", "prix" => 11.80, "image" => "./media/casserole5.webp"),
    array("nom" => "Ensemble casserolles" , "description" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis est diam. Integer mauris sapien, tempor vel scelerisque vel, vulputate nec nisl. Vivamus euismod elementum pulvinar. Sed accumsan semper fermentum.", "catégorie" => "Gravier", "prix" => 22.40, "image" => "./media/casserole6.jpg"),
    array("nom" => "Poelle pyramide" , "description" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis est diam. Integer mauris sapien, tempor vel scelerisque vel, vulputate nec nisl. Vivamus euismod elementum pulvinar. Sed accumsan semper fermentum.", "catégorie" => "Gravier", "prix" => 21.64, "image" => "./media/casserole7.jpg"),
    array("nom" => "Casserolles L. XIV" , "description" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis est diam. Integer mauris sapien, tempor vel scelerisque vel, vulputate nec nisl. Vivamus euismod elementum pulvinar. Sed accumsan semper fermentum.", "catégorie" => "Gravier", "prix" => 22.50, "image" => "./media/casserole8.jpg"),
    array("nom" => "Casserolles Multi" , "description" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis est diam. Integer mauris sapien, tempor vel scelerisque vel, vulputate nec nisl. Vivamus euismod elementum pulvinar. Sed accumsan semper fermentum.", "catégorie" => "Gravier", "prix" => 12.32, "image" => "./media/casserole9.jpeg"),
    array("nom" => "Casserole Alone" , "description" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis est diam. Integer mauris sapien, tempor vel scelerisque vel, vulputate nec nisl. Vivamus euismod elementum pulvinar. Sed accumsan semper fermentum.", "catégorie" => "Gravier", "prix" => 26.43, "image" => "./media/casserole10.webp"),
    array("nom" => "Ensemble Casserolles 2" , "description" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis est diam. Integer mauris sapien, tempor vel scelerisque vel, vulputate nec nisl. Vivamus euismod elementum pulvinar. Sed accumsan semper fermentum.", "catégorie" => "Gravier", "prix" => 21.70, "image" => "./media/casserole1.webp"),
    array("nom" => "Poele Parisienne 2" , "description" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis est diam. Integer mauris sapien, tempor vel scelerisque vel, vulputate nec nisl. Vivamus euismod elementum pulvinar. Sed accumsan semper fermentum.", "catégorie" => "Gravier", "prix" => 34.20, "image" => "./media/casserole5.webp"),
);

?>